"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['nemesys/gui.py']
DATA_FILES = ['nemesys/gui.py']
OPTIONS = {'argv_emulation': True,
 'no_chdir': True,
 'packages': 'wx',
 'plist': 'Info.plist',
 'resources': 'icons',
 'semi_standalone': True,
 'site_packages': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
