"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['nemesys/login.py']
DATA_FILES = ['nemesys/login.py']
OPTIONS = {'argv_emulation': True,
 'plist': 'Info_license.plist',
 'iconfile': 'nemesys.icns',
 'semi_standalone': False,
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
