"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['nemesys/executer.py']
DATA_FILES = ['nemesys/executer.py', 'nemesys/lnemesys.py']
OPTIONS = {'argv_emulation': True,
 'plist': 'Info_executer.plist',
 'resources': 'nemesys/cfg, config',
 'iconfile': 'nemesys.icns',
 'semi_standalone': False,
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
